import SwiftUI

// Gates the app on authentication, then shows the four-tab main UI.
struct RootView: View {
    @Environment(AuthManager.self) private var auth
    @Environment(AppModel.self) private var appModel
    @Environment(\.scenePhase) private var scenePhase

    var body: some View {
        ZStack {
            AppBackground()
            if auth.isSignedIn {
                MainTabView()
                    .task(id: auth.isSignedIn) { appModel.start() }
                    .transition(.opacity.animation(.easeOut(duration: 0.3)))
            } else {
                SignInView()
                    .transition(.opacity.animation(.easeOut(duration: 0.3)))
            }
        }
        // Foreground refresh: a resumed app can be days stale (aired counts, "Out now") — the 20s
        // clock task alone can't fix data. AppModel decides how much staleness warrants a reload.
        .onChange(of: scenePhase) { _, phase in
            guard auth.isSignedIn else { return }
            switch phase {
            case .active: appModel.sceneBecameActive()
            case .background: appModel.sceneEnteredBackground()
            default: break
            }
        }
    }
}

// The four tabs.
enum AppTab: Int, CaseIterable, Hashable {
    case today, schedule, library, discover

    var label: String {
        switch self {
        case .today:    "Today"
        case .schedule: "Schedule"
        case .library:  "Library"
        case .discover: "Add"
        }
    }

    // LocalizedStringKey form for the iOS 26 `Tab(_:image:value:)` initializer.
    var titleKey: LocalizedStringKey {
        switch self {
        case .today:    "Today"
        case .schedule: "Schedule"
        case .library:  "Library"
        case .discover: "Add"
        }
    }

    // Hugeicons tab-bar glyphs (asset-catalog template images, generated by icon/navbar/vector.py).
    // They tint with the accent color when selected and gray when not, just like SF Symbols.
    var icon: String {
        switch self {
        case .today:    "TabToday"
        case .schedule: "TabSchedule"
        case .library:  "TabLibrary"
        case .discover: "TabAdd"
        }
    }
}

// Native tab shell. On iOS 26 the system renders the floating Liquid Glass tab bar and the
// separated search island for a search-role tab.
struct MainTabView: View {
    @Environment(AppModel.self) private var appModel
    @State private var selectedTab: AppTab = .today

    @State private var detail: DetailRoute?
    // Shared namespace for the poster → detail zoom transition; cards register themselves via
    // .zoomSource(...) (surface-scoped ids, see ZoomTransition.swift).
    @Namespace private var zoomNS

    var body: some View {
        @Bindable var model = appModel
        return ZStack(alignment: .bottom) {
            TabView(selection: $selectedTab) {
                Tab(AppTab.today.titleKey, image: AppTab.today.icon, value: AppTab.today) {
                    NavigationStack { TodayView(onOpenDetail: openDetail) }
                        .pageInTransition(isActive: selectedTab == .today)
                }
                Tab(AppTab.schedule.titleKey, image: AppTab.schedule.icon, value: AppTab.schedule) {
                    NavigationStack { ScheduleView(onOpenDetail: openDetail) }
                        .pageInTransition(isActive: selectedTab == .schedule)
                }
                Tab(AppTab.library.titleKey, image: AppTab.library.icon, value: AppTab.library) {
                    NavigationStack { LibraryView(onOpenDetail: openDetail) }
                        .pageInTransition(isActive: selectedTab == .library)
                }
                Tab(value: AppTab.discover, role: .search) {
                    NavigationStack { DiscoverView(onOpenDetail: openDetail) }
                        .searchable(text: $model.searchQuery, prompt: "Search anime & TV")
                        .onSubmit(of: .search) { appModel.recordRecentSearch() }
                }
            }
            .tabViewSearchActivation(.searchTabSelection)
            .sensoryFeedback(.selection, trigger: selectedTab)
            .environment(\.zoomNamespace, zoomNS)

            // Undo/error toasts float above the tab bar. (The detail sheet mounts its own
            // ToastHost — a sheet presents above this whole ZStack.)
            ToastHost()
                .padding(.horizontal, 16)
                .padding(.bottom, 96)
        }
        // Detail zooms out of the tapped card (and shrinks back into it on dismiss); the sheet
        // chrome — rounded corners, grabber, swipe-down — is unchanged. No haptic here: the zoom
        // motion itself is the feedback, and navigation taps stay silent per the HIG.
        .sheet(item: $detail) { route in
            FranchiseDetailView(franchiseId: route.id)
                .presentationDetents([.large])
                .presentationDragIndicator(.visible)
                .navigationTransition(.zoom(sourceID: route.zoomID, in: zoomNS))
        }
    }

    private func openDetail(_ id: String, zoomID: String) {
        detail = DetailRoute(id: id, zoomID: zoomID)
    }
}

// Identifiable wrapper so a franchise id can drive `.sheet(item:)`. `zoomID` is the tapped
// card's matched-transition-source id — the same franchise can have sources in several tabs.
private struct DetailRoute: Identifiable {
    let id: String
    let zoomID: String
}
