import SwiftUI

// Gates the app on authentication, then shows the four-tab main UI.
struct RootView: View {
    @Environment(AuthManager.self) private var auth
    @Environment(AppModel.self) private var appModel
    @Environment(\.scenePhase) private var scenePhase
    // The splash already honors this; the handoff has to as well, or the motion it suppresses
    // just moves one layer up.
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    // Cold-launch splash (the brand beat). Shown once, over everything, then fades to the app.
    @State private var splashDone = false

    var body: some View {
        ZStack {
            ThemeColor.canvas.ignoresSafeArea()
            // The app settles in from a hair small as the splash leaves — the exit reads as
            // moving THROUGH the splash into the app, not a fade between two stills.
            Group {
                if auth.isSignedIn {
                    MainTabView()
                        .task(id: auth.isSignedIn) { appModel.start() }
                        .transition(.opacity.animation(ThemeMotion.uiGentle))
                } else {
                    SignInView()
                        .transition(.opacity.animation(ThemeMotion.uiGentle))
                }
            }
            // Emerges from inside the ident's light: a hair small and slightly defocused,
            // settling to sharp as the splash's zoom-through completes. With Reduce Motion on
            // there is no camera push to emerge from — the splash simply crossfades away.
            .scaleEffect(splashDone || reduceMotion ? 1 : 0.965)
            .blur(radius: splashDone || reduceMotion ? 0 : 4)

            if !splashDone {
                // The splash animates its own zoom-through exit (the camera push in
                // SplashView's timeline), so the container just crossfades over it — the
                // app emerges from inside the icon as it scales past the viewer.
                SplashView { withAnimation(ThemeMotion.uiSettle) { splashDone = true }; appModel.surfaceReady = true }
                    .zIndex(10)
                    .transition(.opacity)
            }
        }
        // Sign-out (chosen, or forced by an expired session) is the one moment the model outlives
        // its account: the library, the live clock, pending episode alerts and a running Live
        // Activity all survive the view tree. Tear them down here so signing in again starts clean.
        .onChange(of: auth.isSignedIn) { _, signedIn in
            if !signedIn { appModel.teardown() }
        }
        // Foreground refresh: a resumed app can be days stale (aired counts, "Out now") — the 20s
        // clock task alone can't fix data. AppModel decides how much staleness warrants a reload.
        .onChange(of: scenePhase) { _, phase in
            guard auth.isSignedIn else { return }
            switch phase {
            case .active: appModel.sceneBecameActive()
            case .background: appModel.sceneEnteredBackground()
            default: break
            }
        }
    }
}

// The four tabs.
enum AppTab: Int, CaseIterable, Hashable {
    case today, schedule, library, discover

    var label: String {
        switch self {
        case .today:    "Today"
        case .schedule: "Schedule"
        case .library:  "Library"
        case .discover: "Add"
        }
    }

    // LocalizedStringKey form for the iOS 26 `Tab(_:image:value:)` initializer.
    var titleKey: LocalizedStringKey {
        switch self {
        case .today:    "Today"
        case .schedule: "Schedule"
        case .library:  "Library"
        case .discover: "Add"
        }
    }

    // Hugeicons tab-bar glyphs (asset-catalog template images, generated by icon/navbar/vector.py).
    // They tint with the accent color when selected and gray when not, just like SF Symbols.
    var icon: String {
        switch self {
        case .today:    "TabToday"
        case .schedule: "TabSchedule"
        case .library:  "TabLibrary"
        case .discover: "TabAdd"
        }
    }
}

// Native tab shell. On iOS 26 the system renders the floating Liquid Glass tab bar and the
// separated search island for a search-role tab.
struct MainTabView: View {
    @Environment(AppModel.self) private var appModel
    @State private var selectedTab: AppTab = .today
    /// One navigation path per tab; Detail and its episode list push onto the active tab's path.
    @State private var paths: [AppTab: NavigationPath] = [:]

    private func path(_ tab: AppTab) -> Binding<NavigationPath> {
        Binding(get: { paths[tab] ?? NavigationPath() }, set: { paths[tab] = $0 })
    }

    /// Re-selecting the active tab pops it to its root (system behaviour, made explicit).
    private var selection: Binding<AppTab> {
        Binding(get: { selectedTab }, set: { tab in
            if tab == selectedTab { paths[tab] = NavigationPath() } else { selectedTab = tab }
        })
    }

    var body: some View {
        ZStack(alignment: .bottom) {
            TabView(selection: selection) {
                Tab(AppTab.today.titleKey, image: AppTab.today.icon, value: AppTab.today) {
                    NavigationStack(path: path(.today)) {
                        TodayView(onOpenDetail: openDetail,
                                  onSeeAllWatching: { selectedTab = .library },
                                  onAddShow: { selectedTab = .discover })
                            .detailDestinations(push: { push(.today, $0) })
                    }
                    .pageInTransition(isActive: selectedTab == .today)
                }
                Tab(AppTab.schedule.titleKey, image: AppTab.schedule.icon, value: AppTab.schedule) {
                    NavigationStack(path: path(.schedule)) {
                        ScheduleView(onOpenDetail: openEpisode, onAddShow: { selectedTab = .discover })
                            .detailDestinations(push: { push(.schedule, $0) })
                    }
                    .pageInTransition(isActive: selectedTab == .schedule)
                }
                Tab(AppTab.library.titleKey, image: AppTab.library.icon, value: AppTab.library) {
                    NavigationStack(path: path(.library)) {
                        LibraryView(onOpenDetail: openDetail,
                                    onAddShow: { selectedTab = .discover })
                            .detailDestinations(push: { push(.library, $0) })
                    }
                    .pageInTransition(isActive: selectedTab == .library)
                }
                Tab(value: AppTab.discover, role: .search) {
                    NavigationStack(path: path(.discover)) {
                        DiscoverView(onOpenDetail: openDetail)
                            .detailDestinations(push: { push(.discover, $0) })
                    }
                    .pageInTransition(isActive: selectedTab == .discover)
                }
            }
            .sensoryFeedback(.selection, trigger: selectedTab)
            .task {
                // One freshness source for every stale strip and Profile's sync line.
                SyncCenter.shared.signals = {
                    .init(lastLoadedAt: appModel.lastLoadedAt, loading: appModel.loading)
                }
                SyncCenter.shared.startMonitoring()
            }

            // Undo / sync / error toasts float above the tab bar, over whatever is pushed.
            ToastHost()
                .padding(.horizontal, 16)
                .padding(.bottom, 58)
        }
    }

    private func push(_ tab: AppTab, _ value: any Hashable) {
        var p = paths[tab] ?? NavigationPath()
        p.append(value)
        paths[tab] = p
    }

    /// Navigation is silent (board 11): no haptic on open.
    private func openDetail(_ id: String, zoomID: String) {
        push(selectedTab, DetailRoute(id: id, zoomID: zoomID))
    }

    /// Schedule variant: lands on a specific season + episode.
    private func openEpisode(_ id: String, zoomID: String, focus: EpisodeFocus?) {
        push(selectedTab, DetailRoute(id: id, zoomID: zoomID, focus: focus))
    }
}

private extension View {
    /// The two destinations every tab can reach: a franchise, and a season's episode list.
    func detailDestinations(push: @escaping (FranchiseDetailView.DetailPush) -> Void) -> some View {
        self
            .navigationDestination(for: DetailRoute.self) { route in
                FranchiseDetailView(franchiseId: route.id, focus: route.focus, push: push)
            }
            .navigationDestination(for: FranchiseDetailView.DetailPush.self) { p in
                switch p {
                case .episodes(let franchiseId, let mediaId, let focusEpisode):
                    SeasonEpisodesView(franchiseId: franchiseId, mediaId: mediaId, focusEpisode: focusEpisode)
                case .history(let franchiseId):
                    WatchHistoryView(franchiseId: franchiseId)
                }
            }
    }
}
